(in-package :cl-user)
(uiop:define-package :cl-couch
  (:use :cl)
  (:nicknames :couch)
  (:export :remove-auth
   :CREATE-MANGO-INDEX
           :NODE-INFO
   :NODE-STATS
           :NODE-RESTART
   :DESIGN-DOCUMENTS
           :COUCHDB-REQUEST
   :ALL-DATABASES
           :OPTIONAL-JS
   :SCHEDULER-JOBS
           :PASSWORD-AUTH
   :NEW-COUCHDB
           :COUCHDB-URL
   :CLUSTER-SETUP
           :SEARCH-ANALYZE
   :SERVER-INFO
           :DATABASE-SHARDS-DOCUMENT
   :BULK-GET-DOCUMENTS*
           :BULK-CREATE-DOCUMENTS*
   :DATABASE-SYNC-SHARDS
           :COUCHDB-HEADERS
   :SAFE-ALIST
           :BULK-CREATE-DOCUMENTS
   :UPDATES
           :DATABASE-EXPLAIN
   :REPLICATE*
           :MANGO-FIND*
   :SHOW-ALL-FBOUNDP-SYMBOLS-OF-PACKAGE
           :SCHEDULER-DOC
   :DATABASE-EXPLAIN*
           :DELETE-DATABASE
   :BULK-GET-DOCUMENTS
           :MANGO-FIND
   :CREATE-DATABASE
           :COUCHDB-COOKIE
   :JWT-AUTH
           :INFO
   :GET-DATABASE
           :GET-DOCUMENT*
   :INFO*
           :MEMBERSHIP
   :MANGO-GET-INDEXES
           :CREATE-DOCUMENT
   :NODE-SYSTEM
           :GET-DOCUMENT
   :CREATE-DOCUMENT*
           :DATABASE-EXISTS-P
   :REPLICATE
           :SCHEDULER-DOCS
   :RESHARD
           :PROXY-AUTH
   :ACTIVE-TASKS
           :DATABASE-SHARDS
   :MANGO-DELETE-INDEX
           :couchdb-client
   :fts-search
           :fts-search*
   :get-view
           :server-info*
   :document-exists-p
           :active-tasks*
   :all-databases*
           :updates*
   :membership*
           :cluster-setup*
   :scheduler-jobs*
           :scheduler-docs*
   :scheduler-doc*
           :node-info*
   :node-stats*
           :node-system*
   :node-restart*
           :search-analyze*
   :reshard*
           :create-database*
   :database-all-documents*
           :database-all-documents
   :delete-database*
           :delete-document
   :delete-document*))
