(in-package :cl-user)
(uiop:define-package :cl-couch
  (:use :cl)
  (:export :remove-auth
   :CREATE-MANGO-INDEX
           :NODE-INFO
   :NODE-STATS
           :DATABASE-DOCUMENTS
   :NODE-RESTART
           :DESIGN-DOCUMENTS
   :COUCHDB-REQUEST
           :ALL-DATABASES
   :OPTIONAL-JS
           :SCHEDULER-JOBS
   :PASSWORD-AUTH
           :NEW-COUCHDB
   :COUCHDB-URL
           :CLUSTER-SETUP
   :SEARCH-ANALYZE
           :SERVER-INFO
   :DATABASE-SHARDS-DOCUMENT
           :BULK-GET-DOCUMENTS*
   :BULK-CREATE-DOCUMENTS*
           :DATABASE-SYNC-SHARDS
   :COUCHDB-HEADERS
           :SAFE-ALIST
   :BULK-CREATE-DOCUMENTS
           :UPDATES
   :DATABASE-EXPLAIN
           :REPLICATE*
   :MANGO-FIND*
           :SHOW-ALL-FBOUNDP-SYMBOLS-OF-PACKAGE
   :SCHEDULER-DOC
           :DATABASE-EXPLAIN*
   :DELETE-DATABASE
           :BULK-GET-DOCUMENTS
   :MANGO-FIND
           :CREATE-DATABASE
   :COUCHDB-COOKIE
           :JWT-AUTH
   :INFO
           :GET-DATABASE
   :GET-DOCUMENT*
           :INFO*
   :MEMBERSHIP
           :MANGO-GET-INDEXES
   :CREATE-DOCUMENT
           :NODE-SYSTEM
   :GET-DOCUMENT
           :CREATE-DOCUMENT*
   :DATABASE-EXISTS-P
           :REPLICATE
   :SCHEDULER-DOCS
           :RESHARD
   :PROXY-AUTH
           :ACTIVE-TASKS
   :DATABASE-SHARDS
           :MANGO-DELETE-INDEX
   :couchdb-client
           :fts-search
   :fts-search*))
